-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE public.users
(
    user_id serial NOT NULL,
    credentials_id integer,
    name character varying(20),
    PRIMARY KEY (user_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.user_credentials
(
    user_id integer,
    login character(20),
    password_hash character(40),
    salt character varying,
    PRIMARY KEY (user_id),
	FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.privacy
(
    privacy_id serial NOT NULL,
    name character varying(20),
    PRIMARY KEY (privacy_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.albums
(
    album_id serial,
    user_id integer,
    privacy_id integer,
    name character varying,
    description text,
    PRIMARY KEY (album_id),
	FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (privacy_id) REFERENCES public.privacy (privacy_id) ON UPDATE CASCADE
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.images
(
    image_id serial NOT NULL,
    user_id integer,
    album_id integer,
    image_sha1 character varying(40),
    PRIMARY KEY (image_id),
	FOREIGN KEY (user_id) REFERENCES public.users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (album_id) REFERENCES public.albums (album_id) ON UPDATE CASCADE
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.image_details
(
    image_id integer NOT NULL,
    name character varying(40),
    description text,
    date date,
    width integer,
    height integer,
    original_name character varying,
    PRIMARY KEY (image_id),
	FOREIGN KEY (image_id) REFERENCES public.images (image_id) ON UPDATE CASCADE ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.tags
(
    tag_id serial NOT NULL,
    name character varying(40),
    PRIMARY KEY (tag_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.tag_order
(
    tag_id integer,
    image_id integer,
	FOREIGN KEY (tag_id) REFERENCES public.tags (tag_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (image_id) REFERENCES public.images (image_id) ON UPDATE CASCADE
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.images_albums
(
    images_album_id integer,
    albums_album_id integer
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public.users_albums
(
    users_user_id integer,
    albums_user_id integer
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public.images_albums
    ADD FOREIGN KEY (albums_album_id)
    REFERENCES public.albums (album_id)
    NOT VALID;


ALTER TABLE public.users_albums
    ADD FOREIGN KEY (users_user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.users_albums
    ADD FOREIGN KEY (albums_user_id)
    REFERENCES public.albums (album_id)
    NOT VALID;


ALTER TABLE public.images_albums
    ADD FOREIGN KEY (images_album_id)
    REFERENCES public.images (image_id)
    NOT VALID;

END;